[mypy]
python_version = 3.12
strict = True
mypy_path = backend/src

[mypy-fastf1.*]
ignore_missing_imports = True

[mypy-statsmodels.*]
ignore_missing_imports = True

[mypy-sklearn.*]
ignore_missing_imports = True
