"""stint fit audit fields

Revision ID: 09e952059b3d
Revises: 1eb268a1b757
Create Date: 2026-09-02 09:37:27.439694
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '09e952059b3d'
down_revision: str | None = '1eb268a1b757'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stint_fits', sa.Column('is_physical', sa.Boolean(), nullable=True), schema='mart')
    op.add_column('stint_fits', sa.Column('tyre_age_range', sa.Double(), nullable=True), schema='mart')
    op.add_column('stint_fits', sa.Column('excluded_lap_count', sa.SmallInteger(), nullable=True), schema='mart')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stint_fits', 'excluded_lap_count', schema='mart')
    op.drop_column('stint_fits', 'tyre_age_range', schema='mart')
    op.drop_column('stint_fits', 'is_physical', schema='mart')
    # ### end Alembic commands ###
