"""lap metrics position

Revision ID: 0bf8e189f16b
Revises: 09e952059b3d
Create Date: 2026-09-02 10:45:16.443391
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0bf8e189f16b'
down_revision: str | None = '09e952059b3d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lap_metrics', sa.Column('position', sa.Double(), nullable=True), schema='mart')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lap_metrics', 'position', schema='mart')
    # ### end Alembic commands ###
