"""circuit fuel effect

Revision ID: 1eb268a1b757
Revises: c94a223cdb03
Create Date: 2026-09-01 18:06:32.053104
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '1eb268a1b757'
down_revision: str | None = 'c94a223cdb03'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circuits', sa.Column('fuel_effect_s_per_kg', sa.Double(), nullable=True, comment='Fitted fuel sensitivity; null means use the default'), schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('circuits', 'fuel_effect_s_per_kg', schema='core')
    # ### end Alembic commands ###
