"""core schema and hypertables

Revision ID: beb9d3fefee0
Revises: 
Create Date: 2026-08-20 11:01:47.962644
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'beb9d3fefee0'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# (table, time column, chunk interval). Telemetry chunks hold roughly one session;
# weather and race control are tiny, so a wider interval avoids chunk sprawl.
HYPERTABLES: list[tuple[str, str, str]] = [
    ("core.telemetry", "ts", "1 day"),
    ("core.positions", "ts", "1 day"),
    ("core.weather", "ts", "7 days"),
    ("core.race_control", "ts", "7 days"),
]

# Compress historical chunks. Segmenting by session+driver keeps a single driver's
# trace contiguous, which is exactly how the telemetry engine reads it.
COMPRESSION: dict[str, tuple[str, str]] = {
    "core.telemetry": ("session_id, driver_number", "ts"),
    "core.positions": ("session_id, driver_number", "ts"),
}


def upgrade() -> None:
    # Enum types are created once here by name. Every column below uses
    # create_type=False so table creation never re-emits the CREATE TYPE.
    session_kind = postgresql.ENUM('FP1', 'FP2', 'FP3', 'Q', 'SQ', 'S', 'R',
                                   name='session_kind', schema='core')
    compound = postgresql.ENUM('SOFT', 'MEDIUM', 'HARD', 'INTERMEDIATE', 'WET',
                               'UNKNOWN', 'TEST_UNKNOWN', name='compound', schema='core')
    event_format = postgresql.ENUM('conventional', 'sprint', 'sprint_shootout',
                                   'sprint_qualifying', 'testing',
                                   name='event_format', schema='core')
    bind = op.get_bind()
    for enum in (session_kind, compound, event_format):
        enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('locality', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('lat', sa.Double(), nullable=True),
    sa.Column('lon', sa.Double(), nullable=True),
    sa.Column('lap_distance_m', sa.Double(), nullable=True),
    sa.Column('pit_lane_loss_s', sa.Double(), nullable=True, comment='Total time lost pitting vs staying out, excluding stationary time'),
    sa.Column('n_corners', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_circuits')),
    sa.UniqueConstraint('key', name=op.f('uq_circuits_key')),
    schema='core'
    )
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('abbreviation', sa.String(length=3), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drivers')),
    sa.UniqueConstraint('key', name=op.f('uq_drivers_key')),
    schema='core'
    )
    op.create_table('seasons',
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('has_telemetry', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('year', name=op.f('pk_seasons')),
    schema='core'
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('key', name=op.f('uq_teams_key')),
    schema='core'
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_year', sa.SmallInteger(), nullable=False),
    sa.Column('round', sa.SmallInteger(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('official_name', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('format', postgresql.ENUM('conventional', 'sprint', 'sprint_shootout', 'sprint_qualifying', 'testing', name='event_format', schema='core', create_type=False), nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['core.circuits.id'], name=op.f('fk_events_circuit_id')),
    sa.ForeignKeyConstraint(['season_year'], ['core.seasons.year'], name=op.f('fk_events_season_year'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('season_year', 'round', name='uq_events_season_round'),
    schema='core'
    )
    op.create_index('ix_events_date', 'events', ['event_date'], unique=False, schema='core')
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('kind', postgresql.ENUM('FP1', 'FP2', 'FP3', 'Q', 'SQ', 'S', 'R', name='session_kind', schema='core', create_type=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('start_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('t0_utc', sa.DateTime(timezone=True), nullable=True, comment='UTC wall-clock corresponding to session time zero'),
    sa.Column('total_laps', sa.SmallInteger(), nullable=True),
    sa.Column('laps_loaded', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('telemetry_loaded', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('weather_loaded', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['core.events.id'], name=op.f('fk_sessions_event_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('event_id', 'kind', name='uq_sessions_event_kind'),
    schema='core'
    )
    op.create_index('ix_sessions_start', 'sessions', ['start_utc'], unique=False, schema='core')
    op.create_table('entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('driver_number', sa.String(length=3), nullable=False),
    sa.Column('team_colour', sa.String(length=9), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['core.drivers.id'], name=op.f('fk_entries_driver_id')),
    sa.ForeignKeyConstraint(['session_id'], ['core.sessions.id'], name=op.f('fk_entries_session_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['core.teams.id'], name=op.f('fk_entries_team_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entries')),
    sa.UniqueConstraint('session_id', 'driver_number', name='uq_entries_session_number'),
    schema='core'
    )
    op.create_index(op.f('ix_entries_session_id'), 'entries', ['session_id'], unique=False, schema='core')
    op.create_table('laps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.String(length=3), nullable=False),
    sa.Column('lap_number', sa.SmallInteger(), nullable=False),
    sa.Column('lap_time_s', sa.Double(), nullable=True),
    sa.Column('sector1_s', sa.Double(), nullable=True),
    sa.Column('sector2_s', sa.Double(), nullable=True),
    sa.Column('sector3_s', sa.Double(), nullable=True),
    sa.Column('lap_start_s', sa.Double(), nullable=True),
    sa.Column('lap_end_s', sa.Double(), nullable=True),
    sa.Column('lap_start_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('speed_i1', sa.Double(), nullable=True),
    sa.Column('speed_i2', sa.Double(), nullable=True),
    sa.Column('speed_fl', sa.Double(), nullable=True),
    sa.Column('speed_st', sa.Double(), nullable=True),
    sa.Column('stint', sa.SmallInteger(), nullable=True),
    sa.Column('compound', postgresql.ENUM('SOFT', 'MEDIUM', 'HARD', 'INTERMEDIATE', 'WET', 'UNKNOWN', 'TEST_UNKNOWN', name='compound', schema='core', create_type=False), nullable=True),
    sa.Column('tyre_life', sa.Double(), nullable=True),
    sa.Column('fresh_tyre', sa.Boolean(), nullable=True),
    sa.Column('pit_in_s', sa.Double(), nullable=True),
    sa.Column('pit_out_s', sa.Double(), nullable=True),
    sa.Column('position', sa.Double(), nullable=True),
    sa.Column('track_status', sa.String(length=16), nullable=True),
    sa.Column('is_personal_best', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_reason', sa.Text(), nullable=True),
    sa.Column('is_accurate', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint('lap_number > 0', name=op.f('ck_laps_lap_number_positive')),
    sa.ForeignKeyConstraint(['session_id'], ['core.sessions.id'], name=op.f('fk_laps_session_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_laps')),
    sa.UniqueConstraint('session_id', 'driver_number', 'lap_number', name='uq_laps_key'),
    schema='core',
    comment='Grain: one row per driver per lap per session'
    )
    op.create_index('ix_laps_session_driver', 'laps', ['session_id', 'driver_number', 'lap_number'], unique=False, schema='core')
    op.create_index('ix_laps_stint', 'laps', ['session_id', 'driver_number', 'stint'], unique=False, schema='core')
    op.create_table('pit_stops',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.String(length=3), nullable=False),
    sa.Column('stop_number', sa.SmallInteger(), nullable=False),
    sa.Column('lap_number', sa.SmallInteger(), nullable=True),
    sa.Column('pit_in_s', sa.Double(), nullable=True),
    sa.Column('pit_out_s', sa.Double(), nullable=True),
    sa.Column('pit_duration_s', sa.Double(), nullable=True),
    sa.Column('compound_in', postgresql.ENUM('SOFT', 'MEDIUM', 'HARD', 'INTERMEDIATE', 'WET', 'UNKNOWN', 'TEST_UNKNOWN', name='compound', schema='core', create_type=False), nullable=True),
    sa.Column('compound_out', postgresql.ENUM('SOFT', 'MEDIUM', 'HARD', 'INTERMEDIATE', 'WET', 'UNKNOWN', 'TEST_UNKNOWN', name='compound', schema='core', create_type=False), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['core.sessions.id'], name=op.f('fk_pit_stops_session_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pit_stops')),
    sa.UniqueConstraint('session_id', 'driver_number', 'stop_number', name='uq_pitstops_key'),
    schema='core'
    )
    op.create_index(op.f('ix_pit_stops_session_id'), 'pit_stops', ['session_id'], unique=False, schema='core')
    op.create_table('positions',
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.String(length=3), nullable=False),
    sa.Column('session_s', sa.Double(), nullable=False),
    sa.Column('x', sa.REAL(), nullable=True),
    sa.Column('y', sa.REAL(), nullable=True),
    sa.Column('z', sa.REAL(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['core.sessions.id'], name=op.f('fk_positions_session_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ts', 'session_id', 'driver_number', name=op.f('pk_positions')),
    schema='core',
    comment='Hypertable. Grain: one row per driver per position sample'
    )
    op.create_index('ix_positions_session_driver_ts', 'positions', ['session_id', 'driver_number', 'ts'], unique=False, schema='core')
    op.create_table('race_control',
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('session_s', sa.Double(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('flag', sa.String(length=32), nullable=True),
    sa.Column('scope', sa.String(length=32), nullable=True),
    sa.Column('sector', sa.SmallInteger(), nullable=True),
    sa.Column('driver_number', sa.String(length=3), nullable=True),
    sa.Column('lap_number', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['core.sessions.id'], name=op.f('fk_race_control_session_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ts', 'session_id', 'seq', name=op.f('pk_race_control')),
    schema='core',
    comment='Hypertable. Grain: one row per message'
    )
    op.create_index('ix_race_control_session_ts', 'race_control', ['session_id', 'ts'], unique=False, schema='core')
    op.create_table('results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Double(), nullable=True),
    sa.Column('classified_position', sa.String(length=4), nullable=True),
    sa.Column('grid_position', sa.Double(), nullable=True),
    sa.Column('points', sa.Double(), nullable=True),
    sa.Column('laps_completed', sa.Double(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('total_time_s', sa.Double(), nullable=True),
    sa.Column('q1_s', sa.Double(), nullable=True),
    sa.Column('q2_s', sa.Double(), nullable=True),
    sa.Column('q3_s', sa.Double(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['core.drivers.id'], name=op.f('fk_results_driver_id')),
    sa.ForeignKeyConstraint(['session_id'], ['core.sessions.id'], name=op.f('fk_results_session_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['core.teams.id'], name=op.f('fk_results_team_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_results')),
    sa.UniqueConstraint('session_id', 'driver_id', name='uq_results_session_driver'),
    schema='core'
    )
    op.create_index(op.f('ix_results_session_id'), 'results', ['session_id'], unique=False, schema='core')
    op.create_table('stints',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.String(length=3), nullable=False),
    sa.Column('stint', sa.SmallInteger(), nullable=False),
    sa.Column('compound', postgresql.ENUM('SOFT', 'MEDIUM', 'HARD', 'INTERMEDIATE', 'WET', 'UNKNOWN', 'TEST_UNKNOWN', name='compound', schema='core', create_type=False), nullable=True),
    sa.Column('start_lap', sa.SmallInteger(), nullable=True),
    sa.Column('end_lap', sa.SmallInteger(), nullable=True),
    sa.Column('n_laps', sa.SmallInteger(), nullable=True),
    sa.Column('tyre_age_start', sa.Double(), nullable=True),
    sa.Column('fresh_tyre', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['core.sessions.id'], name=op.f('fk_stints_session_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stints')),
    sa.UniqueConstraint('session_id', 'driver_number', 'stint', name='uq_stints_key'),
    schema='core'
    )
    op.create_index(op.f('ix_stints_session_id'), 'stints', ['session_id'], unique=False, schema='core')
    op.create_table('telemetry',
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.String(length=3), nullable=False),
    sa.Column('session_s', sa.Double(), nullable=False),
    sa.Column('speed', sa.REAL(), nullable=True),
    sa.Column('rpm', sa.REAL(), nullable=True),
    sa.Column('gear', sa.SmallInteger(), nullable=True),
    sa.Column('throttle', sa.REAL(), nullable=True),
    sa.Column('brake', sa.Boolean(), nullable=True),
    sa.Column('drs', sa.SmallInteger(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['core.sessions.id'], name=op.f('fk_telemetry_session_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ts', 'session_id', 'driver_number', name=op.f('pk_telemetry')),
    schema='core',
    comment='Hypertable. Grain: one row per driver per telemetry sample'
    )
    op.create_index('ix_telemetry_session_driver_ts', 'telemetry', ['session_id', 'driver_number', 'ts'], unique=False, schema='core')
    op.create_table('weather',
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('session_s', sa.Double(), nullable=False),
    sa.Column('air_temp', sa.REAL(), nullable=True),
    sa.Column('track_temp', sa.REAL(), nullable=True),
    sa.Column('humidity', sa.REAL(), nullable=True),
    sa.Column('pressure', sa.REAL(), nullable=True),
    sa.Column('wind_speed', sa.REAL(), nullable=True),
    sa.Column('wind_direction', sa.SmallInteger(), nullable=True),
    sa.Column('rainfall', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['core.sessions.id'], name=op.f('fk_weather_session_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ts', 'session_id', name=op.f('pk_weather')),
    schema='core',
    comment='Hypertable. Grain: one row per session per sample'
    )
    op.create_index('ix_weather_session_ts', 'weather', ['session_id', 'ts'], unique=False, schema='core')
    op.create_table('lap_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.String(length=3), nullable=False),
    sa.Column('lap_number', sa.SmallInteger(), nullable=False),
    sa.Column('lap_time_s', sa.Double(), nullable=True),
    sa.Column('is_green', sa.Boolean(), nullable=True),
    sa.Column('is_in_lap', sa.Boolean(), nullable=True),
    sa.Column('is_out_lap', sa.Boolean(), nullable=True),
    sa.Column('is_representative', sa.Boolean(), nullable=True),
    sa.Column('exclusion_reason', sa.String(length=32), nullable=True),
    sa.Column('fuel_corrected_s', sa.Double(), nullable=True),
    sa.Column('fuel_load_kg', sa.Double(), nullable=True),
    sa.Column('evolution_corrected_s', sa.Double(), nullable=True),
    sa.Column('gap_ahead_s', sa.Double(), nullable=True),
    sa.Column('gap_behind_s', sa.Double(), nullable=True),
    sa.Column('is_clean_air', sa.Boolean(), nullable=True),
    sa.Column('stint', sa.SmallInteger(), nullable=True),
    sa.Column('compound', sa.String(length=16), nullable=True),
    sa.Column('tyre_life', sa.Double(), nullable=True),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['core.sessions.id'], name=op.f('fk_lap_metrics_session_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lap_metrics')),
    sa.UniqueConstraint('session_id', 'driver_number', 'lap_number', 'engine_version', name='uq_lap_metrics_key'),
    schema='mart',
    comment='Derived per-lap facts; recomputable from core'
    )
    op.create_index('ix_lap_metrics_representative', 'lap_metrics', ['session_id', 'driver_number'], unique=False, schema='mart', postgresql_where=sa.text('is_representative'))
    op.create_index('ix_lap_metrics_session', 'lap_metrics', ['session_id', 'engine_version'], unique=False, schema='mart')
    # ### end Alembic commands ###

    # --- TimescaleDB ----------------------------------------------------
    # Autogenerate cannot express any of the following.
    for table, time_col, interval in HYPERTABLES:
        # migrate_data moves the (empty at this point) rows; if_not_exists keeps the
        # migration re-runnable against a partially provisioned database.
        op.execute(
            f"SELECT create_hypertable('{table}', '{time_col}', "
            f"chunk_time_interval => INTERVAL '{interval}', "
            f"if_not_exists => TRUE, migrate_data => TRUE)"
        )

    for table, (segment_by, order_by) in COMPRESSION.items():
        op.execute(
            f"ALTER TABLE {table} SET ("
            f"timescaledb.compress, "
            f"timescaledb.compress_segmentby = '{segment_by}', "
            f"timescaledb.compress_orderby = '{order_by}')"
        )
        # Race weekends are analysed for days afterwards; compress once that is over.
        op.execute(f"SELECT add_compression_policy('{table}', INTERVAL '7 days')")

    # Per-lap telemetry summary. Precomputes the aggregates every pace and telemetry
    # view asks for, so the dashboard never scans raw 4 Hz data for a summary stat.
    op.execute("""
        CREATE MATERIALIZED VIEW mart.telemetry_lap_summary
        WITH (timescaledb.continuous) AS
        SELECT
            time_bucket(INTERVAL '1 minute', ts) AS bucket,
            session_id,
            driver_number,
            count(*)                                          AS n_samples,
            avg(speed)                                        AS avg_speed,
            max(speed)                                        AS max_speed,
            min(speed)                                        AS min_speed,
            avg(throttle)                                     AS avg_throttle,
            avg(rpm)                                          AS avg_rpm,
            max(gear)                                         AS max_gear,
            100.0 * count(*) FILTER (WHERE brake)   / count(*) AS pct_braking,
            100.0 * count(*) FILTER (WHERE throttle >= 99) / count(*) AS pct_full_throttle,
            100.0 * count(*) FILTER (WHERE drs IN (10, 12, 14)) / count(*) AS pct_drs_open
        FROM core.telemetry
        GROUP BY bucket, session_id, driver_number
        WITH NO DATA
    """)
    op.execute(
        "SELECT add_continuous_aggregate_policy('mart.telemetry_lap_summary', "
        "start_offset => INTERVAL '30 days', "
        "end_offset => INTERVAL '1 hour', "
        "schedule_interval => INTERVAL '1 hour')"
    )


def downgrade() -> None:
    # Drop Timescale objects before the tables they depend on.
    op.execute("DROP MATERIALIZED VIEW IF EXISTS mart.telemetry_lap_summary")
    for table in COMPRESSION:
        op.execute(f"SELECT remove_compression_policy('{table}', if_exists => TRUE)")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lap_metrics_session', table_name='lap_metrics', schema='mart')
    op.drop_index('ix_lap_metrics_representative', table_name='lap_metrics', schema='mart', postgresql_where=sa.text('is_representative'))
    op.drop_table('lap_metrics', schema='mart')
    op.drop_index('ix_weather_session_ts', table_name='weather', schema='core')
    op.drop_table('weather', schema='core')
    op.drop_index('ix_telemetry_session_driver_ts', table_name='telemetry', schema='core')
    op.drop_table('telemetry', schema='core')
    op.drop_index(op.f('ix_stints_session_id'), table_name='stints', schema='core')
    op.drop_table('stints', schema='core')
    op.drop_index(op.f('ix_results_session_id'), table_name='results', schema='core')
    op.drop_table('results', schema='core')
    op.drop_index('ix_race_control_session_ts', table_name='race_control', schema='core')
    op.drop_table('race_control', schema='core')
    op.drop_index('ix_positions_session_driver_ts', table_name='positions', schema='core')
    op.drop_table('positions', schema='core')
    op.drop_index(op.f('ix_pit_stops_session_id'), table_name='pit_stops', schema='core')
    op.drop_table('pit_stops', schema='core')
    op.drop_index('ix_laps_stint', table_name='laps', schema='core')
    op.drop_index('ix_laps_session_driver', table_name='laps', schema='core')
    op.drop_table('laps', schema='core')
    op.drop_index(op.f('ix_entries_session_id'), table_name='entries', schema='core')
    op.drop_table('entries', schema='core')
    op.drop_index('ix_sessions_start', table_name='sessions', schema='core')
    op.drop_table('sessions', schema='core')
    op.drop_index('ix_events_date', table_name='events', schema='core')
    op.drop_table('events', schema='core')
    op.drop_table('teams', schema='core')
    op.drop_table('seasons', schema='core')
    op.drop_table('drivers', schema='core')
    op.drop_table('circuits', schema='core')
    # ### end Alembic commands ###

    op.execute("DROP TYPE IF EXISTS core.event_format")
    op.execute("DROP TYPE IF EXISTS core.compound")
    op.execute("DROP TYPE IF EXISTS core.session_kind")
