"""pace and degradation marts

Revision ID: c94a223cdb03
Revises: e493fb92ac07
Create Date: 2026-09-01 14:38:44.410575
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'c94a223cdb03'
down_revision: str | None = 'e493fb92ac07'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('degradation_curves',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('compound', sa.String(length=16), nullable=False),
    sa.Column('n_stints', sa.SmallInteger(), nullable=True),
    sa.Column('n_laps', sa.Integer(), nullable=True),
    sa.Column('degradation_s_per_lap', sa.Double(), nullable=True),
    sa.Column('degradation_iqr_s', sa.Double(), nullable=True),
    sa.Column('median_pace_s', sa.Double(), nullable=True),
    sa.Column('max_stint_laps', sa.SmallInteger(), nullable=True),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['core.sessions.id'], name=op.f('fk_degradation_curves_session_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_degradation_curves')),
    sa.UniqueConstraint('session_id', 'compound', 'engine_version', name='uq_degradation_curves_key'),
    schema='mart',
    comment='Per-compound degradation; recomputable'
    )
    op.create_table('pace_rankings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.String(length=3), nullable=False),
    sa.Column('n_laps', sa.SmallInteger(), nullable=True),
    sa.Column('pace_s', sa.Double(), nullable=True),
    sa.Column('best_s', sa.Double(), nullable=True),
    sa.Column('median_s', sa.Double(), nullable=True),
    sa.Column('std_s', sa.Double(), nullable=True),
    sa.Column('clean_air_laps', sa.SmallInteger(), nullable=True),
    sa.Column('gap_to_best_s', sa.Double(), nullable=True),
    sa.Column('rank', sa.SmallInteger(), nullable=True),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['core.sessions.id'], name=op.f('fk_pace_rankings_session_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pace_rankings')),
    sa.UniqueConstraint('session_id', 'driver_number', 'engine_version', name='uq_pace_rankings_key'),
    schema='mart',
    comment='Per-driver session pace; recomputable'
    )
    op.create_index('ix_pace_rankings_session', 'pace_rankings', ['session_id', 'engine_version'], unique=False, schema='mart')
    op.create_table('stint_fits',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.String(length=3), nullable=False),
    sa.Column('stint', sa.SmallInteger(), nullable=False),
    sa.Column('compound', sa.String(length=16), nullable=True),
    sa.Column('n_laps', sa.SmallInteger(), nullable=True),
    sa.Column('pace_s', sa.Double(), nullable=True),
    sa.Column('degradation_s_per_lap', sa.Double(), nullable=True),
    sa.Column('r_squared', sa.Double(), nullable=True),
    sa.Column('residual_std_s', sa.Double(), nullable=True),
    sa.Column('tyre_age_start', sa.Double(), nullable=True),
    sa.Column('is_reliable', sa.Boolean(), nullable=True),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['core.sessions.id'], name=op.f('fk_stint_fits_session_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stint_fits')),
    sa.UniqueConstraint('session_id', 'driver_number', 'stint', 'engine_version', name='uq_stint_fits_key'),
    schema='mart',
    comment='Per-stint pace/degradation split; recomputable'
    )
    op.create_index('ix_stint_fits_session', 'stint_fits', ['session_id', 'engine_version'], unique=False, schema='mart')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stint_fits_session', table_name='stint_fits', schema='mart')
    op.drop_table('stint_fits', schema='mart')
    op.drop_index('ix_pace_rankings_session', table_name='pace_rankings', schema='mart')
    op.drop_table('pace_rankings', schema='mart')
    op.drop_table('degradation_curves', schema='mart')
    # ### end Alembic commands ###
