/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Seasons
         * @description Every ingested season.
         */
        get: operations["list_seasons_api_v1_seasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Events
         * @description Grand prix weekends, newest first.
         */
        get: operations["list_events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description Timed sessions. Every analysis endpoint is keyed by one of these ids.
         */
        get: operations["list_sessions_api_v1_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session
         * @description One session.
         */
        get: operations["get_session_api_v1_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/laps/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Laps
         * @description Per-lap metrics, including why any lap was excluded.
         */
        get: operations["get_laps_api_v1_analysis_laps__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/pace/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pace
         * @description Driver pace, ranked.
         *
         *     Pace is the 20th percentile of clean fuel-corrected laps — not the fastest lap,
         *     which rewards whoever had the best single opportunity, and not the mean, which
         *     rewards whoever avoided traffic.
         */
        get: operations["get_pace_api_v1_analysis_pace__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/degradation/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Degradation
         * @description Tyre degradation by compound, with the stint fits behind it.
         *
         *     A stint fit may report a negative slope when the run was too short to support an
         *     estimate. Those are returned with ``is_physical`` false rather than hidden — the
         *     failure is information about the stint.
         */
        get: operations["get_degradation_api_v1_analysis_degradation__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategy/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Strategy
         * @description Pit loss and ranked stop strategies.
         *
         *     Pit loss is measured from the laps either side of a stop, not from pit-lane
         *     transit time: the cost of stopping is how much the in-lap and out-lap together
         *     exceed two normal laps.
         */
        get: operations["get_strategy_api_v1_strategy__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/undercut/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Undercut
         * @description Every lap where a driver was close enough behind to try an undercut.
         *
         *     The arithmetic is a race between two quantities: pitting costs the net pit loss
         *     and gains the difference between fresh-tyre pace and the rival's degraded pace,
         *     compounded over the laps before they respond. Calls inside half a second either
         *     way are reported as marginal rather than decided.
         */
        get: operations["get_undercut_api_v1_undercut__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stints/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stints
         * @description Tyre stints per driver, for a strategy timeline.
         */
        get: operations["get_stints_api_v1_stints__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulate/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Simulate Race
         * @description Compare strategies by simulating the race many times.
         *
         *     A single "four seconds faster" is misleading; what matters is how often a strategy
         *     wins once safety cars and lap-time noise are resampled. All strategies share one
         *     seed so they face the same sampled races.
         */
        get: operations["simulate_race_api_v1_simulate__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ratings/{season}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ratings
         * @description Composite driver ratings for one season.
         *
         *     Scores are min-max normalised across the field being compared, so they rank
         *     drivers within a season and carry no meaning across seasons.
         */
        get: operations["get_ratings_api_v1_ratings__season__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teammates/{season}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Teammates
         * @description Head-to-head pace between drivers who shared a car.
         *
         *     The closest thing the sport has to a controlled comparison: same machinery, same
         *     upgrades, same weekend. Strategy splits, damage and traffic are still not
         *     controlled for, so a thin pairing is flagged rather than presented as settled.
         */
        get: operations["get_teammates_api_v1_teammates__season__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/telemetry/compare/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare Laps
         * @description Compare two laps: cumulative delta time and corner-by-corner minimum speeds.
         *
         *     The delta trace answers *where* a lap was won, not just by how much. A step down
         *     under braking is a later brake point; a rise on the straight after a corner means
         *     the time was actually won in the corner before it.
         */
        get: operations["compare_laps_api_v1_telemetry_compare__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/telemetry/map/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Track Map
         * @description The circuit drawn from one lap's positional trace, coloured by speed.
         *
         *     Nothing about the circuit is stored: the shape comes from where the car actually
         *     went, so any layout the pipeline has data for can be drawn without a map to
         *     maintain. Corner apexes are placed by translating the detected distance back onto
         *     the geometry.
         */
        get: operations["track_map_api_v1_telemetry_map__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness and dependency check, for a load balancer or `f1x doctor`.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CornerDeltaOut */
        CornerDeltaOut: {
            /** Index */
            index: number;
            /** Apex Distance M */
            apex_distance_m: number;
            /** Reference Min Speed Kmh */
            reference_min_speed_kmh: number;
            /** Comparison Min Speed Kmh */
            comparison_min_speed_kmh: number;
            /** Delta Kmh */
            delta_kmh: number;
        };
        /** CornerOut */
        CornerOut: {
            /** Index */
            index: number;
            /** Apex Distance M */
            apex_distance_m: number;
            /** Min Speed Kmh */
            min_speed_kmh: number;
            /** Entry Speed Kmh */
            entry_speed_kmh: number;
            /** Exit Speed Kmh */
            exit_speed_kmh: number;
            /** Braking Point M */
            braking_point_m?: number | null;
            /** Throttle Point M */
            throttle_point_m?: number | null;
        };
        /** DegradationOut */
        DegradationOut: {
            /** Compound */
            compound: string;
            /** N Stints */
            n_stints: number;
            /** N Laps */
            n_laps: number;
            /**
             * Degradation S Per Lap
             * @description Median slope across reliable stints on this compound
             */
            degradation_s_per_lap: number;
            /**
             * Degradation Iqr S
             * @description Interquartile spread: the honest width of the estimate
             */
            degradation_iqr_s: number;
            /** Median Pace S */
            median_pace_s: number;
            /**
             * Max Stint Laps
             * @description Longest observed stint. Predictions beyond this extrapolate.
             */
            max_stint_laps: number;
        };
        /** DegradationResponse */
        DegradationResponse: {
            /** Session Id */
            session_id: number;
            meta: components["schemas"]["Meta"];
            /** Compounds */
            compounds: components["schemas"]["DegradationOut"][];
            /** Stints */
            stints: components["schemas"]["StintFitOut"][];
        };
        /** DriverRatingOut */
        DriverRatingOut: {
            /** Driver Number */
            driver_number: string;
            /** Rank */
            rank: number;
            /** N Races */
            n_races: number;
            /** Overall */
            overall: number;
            /** Pace */
            pace: number;
            /** Racecraft */
            racecraft: number;
            /** Consistency */
            consistency: number;
            /** Tyre Management */
            tyre_management: number;
            /** Strongest */
            strongest: string;
        };
        /** EventOut */
        EventOut: {
            /** Id */
            id: number;
            /** Season Year */
            season_year: number;
            /** Round */
            round: number;
            /** Name */
            name: string;
            /** Country */
            country?: string | null;
            /** Circuit Key */
            circuit_key?: string | null;
            /** Event Date */
            event_date?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LapOut */
        LapOut: {
            /** Driver Number */
            driver_number: string;
            /** Lap Number */
            lap_number: number;
            /** Lap Time S */
            lap_time_s?: number | null;
            /** Compound */
            compound?: string | null;
            /** Tyre Life */
            tyre_life?: number | null;
            /** Stint */
            stint?: number | null;
            /** Position */
            position?: number | null;
            /**
             * Is Representative
             * @description Whether this lap belongs in a pace sample
             */
            is_representative?: boolean | null;
            /**
             * Exclusion Reason
             * @description Why the lap was excluded, when it was
             */
            exclusion_reason?: string | null;
            /**
             * Fuel Corrected S
             * @description Lap time corrected to an empty-tank equivalent using a published 0.030 s/kg coefficient. An estimate, not measured fuel telemetry.
             */
            fuel_corrected_s?: number | null;
        };
        /**
         * Meta
         * @description Provenance attached to every analysis response.
         */
        Meta: {
            /**
             * Engine Version
             * @description Engine version that produced these values
             */
            engine_version: string;
            /**
             * Computed At
             * @description When the underlying metrics were computed
             */
            computed_at?: string | null;
        };
        /** PaceOut */
        PaceOut: {
            /** Driver Number */
            driver_number: string;
            /** Rank */
            rank: number;
            /** N Laps */
            n_laps: number;
            /**
             * Pace S
             * @description 20th percentile of clean fuel-corrected laps, not the fastest lap
             */
            pace_s: number;
            /** Gap To Best S */
            gap_to_best_s: number;
            /** Best S */
            best_s: number;
            /** Median S */
            median_s: number;
            /**
             * Std S
             * @description Lap-time spread: lower is more consistent
             */
            std_s: number;
            /** Clean Air Laps */
            clean_air_laps: number;
        };
        /** PaceResponse */
        PaceResponse: {
            /** Session Id */
            session_id: number;
            meta: components["schemas"]["Meta"];
            /** Drivers */
            drivers: components["schemas"]["PaceOut"][];
        };
        /** PitLossOut */
        PitLossOut: {
            /** N Stops */
            n_stops: number;
            /**
             * Pit Window S
             * @description Pit entry to pit exit: transit only
             */
            pit_window_s: number;
            /** Reference Lap S */
            reference_lap_s: number;
            /**
             * Net Loss S
             * @description What a stop actually costs: how much the in-lap and out-lap together exceed two normal laps
             */
            net_loss_s: number;
            /** Spread S */
            spread_s: number;
        };
        /** RatingsResponse */
        RatingsResponse: {
            /** Season */
            season: number;
            meta: components["schemas"]["Meta"];
            /**
             * Note
             * @description Ratings are min-max normalised, so cross-season comparison is meaningless
             * @default Scores are relative to this season's field, not an absolute scale.
             */
            note: string;
            /** Drivers */
            drivers: components["schemas"]["DriverRatingOut"][];
        };
        /** SeasonOut */
        SeasonOut: {
            /** Year */
            year: number;
            /** N Events */
            n_events: number;
            /**
             * Has Telemetry
             * @description Whether car telemetry exists for this season (2018 onward)
             */
            has_telemetry: boolean;
        };
        /** SessionOut */
        SessionOut: {
            /** Id */
            id: number;
            /** Event Id */
            event_id: number;
            /**
             * Kind
             * @description FP1-3, Q, SQ, S or R
             */
            kind: string;
            /** Event Name */
            event_name: string;
            /** Season Year */
            season_year: number;
            /** Round */
            round: number;
            /** Total Laps */
            total_laps?: number | null;
            /** Telemetry Loaded */
            telemetry_loaded: boolean;
            /** Start Utc */
            start_utc?: string | null;
        };
        /** SimulatedStrategyOut */
        SimulatedStrategyOut: {
            /** N Stops */
            n_stops: number;
            /** Stint Lengths */
            stint_lengths: number[];
            /** Median S */
            median_s: number;
            /** P5 S */
            p5_s: number;
            /** P95 S */
            p95_s: number;
            /**
             * Spread S
             * @description Width of the middle 90 % of outcomes
             */
            spread_s: number;
            /**
             * Win Rate
             * @description Share of simulated races this strategy won
             */
            win_rate: number;
        };
        /** SimulationResponse */
        SimulationResponse: {
            /** Session Id */
            session_id: number;
            meta: components["schemas"]["Meta"];
            /** Iterations */
            iterations: number;
            /** Safety Car Rate */
            safety_car_rate: number;
            /**
             * Is Decisive
             * @description False when the leading strategy wins too rarely to call it
             */
            is_decisive: boolean;
            /** Strategies */
            strategies: components["schemas"]["SimulatedStrategyOut"][];
        };
        /** StintFitOut */
        StintFitOut: {
            /** Driver Number */
            driver_number: string;
            /** Stint */
            stint: number;
            /** Compound */
            compound?: string | null;
            /** N Laps */
            n_laps: number;
            /**
             * Pace S
             * @description Fitted lap time at zero tyre age
             */
            pace_s: number;
            /**
             * Degradation S Per Lap
             * @description Fitted slope. May be negative when the stint was too short to support an estimate; see is_physical.
             */
            degradation_s_per_lap: number;
            /**
             * Is Physical
             * @description False when the fitted slope is negative. Tyres do not gain time with age, so such a fit means the stint gave too little usable range.
             */
            is_physical?: boolean | null;
            /** Is Reliable */
            is_reliable?: boolean | null;
            /** R Squared */
            r_squared?: number | null;
            /**
             * Tyre Age Range
             * @description Span of tyre age the fit actually covered
             */
            tyre_age_range?: number | null;
            /**
             * Excluded Lap Count
             * @description Laps the warm-up cutoff removed before fitting
             */
            excluded_lap_count?: number | null;
        };
        /**
         * StintOut
         * @description One run on a set of tyres, for the timeline.
         */
        StintOut: {
            /** Driver Number */
            driver_number: string;
            /** Stint */
            stint: number;
            /** Compound */
            compound?: string | null;
            /** Start Lap */
            start_lap: number;
            /** End Lap */
            end_lap: number;
            /** N Laps */
            n_laps: number;
            /** Tyre Age Start */
            tyre_age_start?: number | null;
            /** Fresh Tyre */
            fresh_tyre?: boolean | null;
        };
        /** StintTimelineResponse */
        StintTimelineResponse: {
            /** Session Id */
            session_id: number;
            /** Total Laps */
            total_laps?: number | null;
            /** Stints */
            stints: components["schemas"]["StintOut"][];
        };
        /** StrategyOptionOut */
        StrategyOptionOut: {
            /** N Stops */
            n_stops: number;
            /** Stint Lengths */
            stint_lengths: number[];
            /** Degradation Cost S */
            degradation_cost_s: number;
            /** Pit Cost S */
            pit_cost_s: number;
            /** Total Cost S */
            total_cost_s: number;
        };
        /** StrategyResponse */
        StrategyResponse: {
            /** Session Id */
            session_id: number;
            meta: components["schemas"]["Meta"];
            pit_loss: components["schemas"]["PitLossOut"];
            /**
             * Options
             * @description Ranked cheapest first. A dry race mandates at least one stop.
             */
            options: components["schemas"]["StrategyOptionOut"][];
        };
        /**
         * TeammateDeltaOut
         * @description One pairing's head-to-head over the sessions they both completed.
         */
        TeammateDeltaOut: {
            /** Team Key */
            team_key?: string | null;
            /** Driver A */
            driver_a: string;
            /** Driver B */
            driver_b: string;
            /** N Sessions */
            n_sessions: number;
            /** Faster Driver */
            faster_driver: string;
            /**
             * Margin S
             * @description Median pace gap between the pair, in seconds per lap
             */
            margin_s: number;
            /**
             * Median Delta S
             * @description Signed gap: negative means driver_a was quicker
             */
            median_delta_s: number;
            /**
             * Std Delta S
             * @description Spread across sessions. A small margin with a large spread is not settled.
             */
            std_delta_s: number;
            /** Sessions A Ahead */
            sessions_a_ahead: number;
            /** Sessions B Ahead */
            sessions_b_ahead: number;
            /**
             * Is Decisive
             * @description True when one driver led at least 70% of shared sessions, not just on average
             */
            is_decisive: boolean;
            /** Is Reliable */
            is_reliable: boolean;
        };
        /** TeammatesResponse */
        TeammatesResponse: {
            /** Season */
            season: number;
            meta: components["schemas"]["Meta"];
            /**
             * Note
             * @default Same car, so the difference is mostly the driver — but strategy splits, damage and traffic are not controlled for.
             */
            note: string;
            /** Pairings */
            pairings: components["schemas"]["TeammateDeltaOut"][];
        };
        /** TelemetryCompareResponse */
        TelemetryCompareResponse: {
            /** Session Id */
            session_id: number;
            meta: components["schemas"]["Meta"];
            /** Reference Driver */
            reference_driver: string;
            /** Comparison Driver */
            comparison_driver: string;
            /**
             * Final Delta S
             * @description Lap-time difference. Negative means the comparison lap was quicker.
             */
            final_delta_s: number;
            /**
             * Distance M
             * @description Common distance grid, one metre apart
             */
            distance_m: number[];
            /**
             * Delta S
             * @description Cumulative time difference at each point on the lap
             */
            delta_s: number[];
            /** Corners */
            corners: components["schemas"]["CornerDeltaOut"][];
        };
        /** TrackMapResponse */
        TrackMapResponse: {
            /** Session Id */
            session_id: number;
            meta: components["schemas"]["Meta"];
            /** Driver Number */
            driver_number: string;
            /** Lap Number */
            lap_number: number;
            /** Lap Time S */
            lap_time_s?: number | null;
            /**
             * Lap Distance M
             * @description Integrated from speed, so within a percent or two of the official length
             */
            lap_distance_m: number;
            /** Min Speed Kmh */
            min_speed_kmh: number;
            /** Max Speed Kmh */
            max_speed_kmh: number;
            /** Points */
            points: components["schemas"]["TrackPointOut"][];
            /**
             * Corners
             * @description Detected corners, with the map coordinate of each apex
             */
            corners: components["schemas"]["CornerOut"][];
        };
        /**
         * TrackPointOut
         * @description One sample of the racing line, with the speed carried there.
         */
        TrackPointOut: {
            /**
             * X
             * @description Track coordinate, normalised to 0-1000
             */
            x: number;
            /** Y */
            y: number;
            /** Speed Kmh */
            speed_kmh: number;
            /** Distance M */
            distance_m: number;
        };
        /** UndercutResponse */
        UndercutResponse: {
            /** Session Id */
            session_id: number;
            meta: components["schemas"]["Meta"];
            /** Degradation S Per Lap */
            degradation_s_per_lap: number;
            /** Net Pit Loss S */
            net_pit_loss_s: number;
            /** Windows */
            windows: components["schemas"]["UndercutWindowOut"][];
        };
        /**
         * UndercutWindowOut
         * @description One lap where a driver was close enough behind to try an undercut.
         */
        UndercutWindowOut: {
            /** Lap Number */
            lap_number: number;
            /** Attacker */
            attacker: string;
            /** Defender */
            defender: string;
            /** Gap S */
            gap_s: number;
            /**
             * Gain Per Lap S
             * @description Per-lap advantage a fresh set gives over the rival's worn tyres
             */
            gain_per_lap_s: number;
            /** Total Gain S */
            total_gain_s: number;
            /**
             * Margin S
             * @description How much the undercut wins or misses by. Negative means it fails.
             */
            margin_s: number;
            /**
             * Verdict
             * @description undercut, hold, or marginal
             */
            verdict: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_seasons_api_v1_seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonOut"][];
                };
            };
        };
    };
    list_events_api_v1_events_get: {
        parameters: {
            query?: {
                /** @description Restrict to one season */
                season?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_v1_sessions_get: {
        parameters: {
            query?: {
                season?: number | null;
                /** @description FP1-3, Q, SQ, S or R */
                kind?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_v1_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_laps_api_v1_analysis_laps__session_id__get: {
        parameters: {
            query?: {
                /** @description Restrict to one car number */
                driver?: string | null;
                /** @description Only laps that belong in a pace sample */
                representative_only?: boolean;
            };
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LapOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pace_api_v1_analysis_pace__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_degradation_api_v1_analysis_degradation__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DegradationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_strategy_api_v1_strategy__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_undercut_api_v1_undercut__session_id__get: {
        parameters: {
            query?: {
                max_gap_s?: number;
            };
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UndercutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stints_api_v1_stints__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StintTimelineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_race_api_v1_simulate__session_id__get: {
        parameters: {
            query?: {
                iterations?: number;
            };
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ratings_api_v1_ratings__season__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_teammates_api_v1_teammates__season__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeammatesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_laps_api_v1_telemetry_compare__session_id__get: {
        parameters: {
            query: {
                driver_a: string;
                lap_a: number;
                driver_b: string;
                lap_b: number;
            };
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryCompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    track_map_api_v1_telemetry_map__session_id__get: {
        parameters: {
            query: {
                driver: string;
                lap: number;
            };
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackMapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
